### ISSUE TITLE
CustomBuildMenuItem_2018 error in Unity 5.6.5p4

### ISSUE THREAD

**Issue by trinhvietvan** [Aptoide/bds-unity-plugin#1]
Error on line 63 in file CustomBuildMenuItem_2018.cs
`BuildPipeline.BuildPlayer` method in now return a error string, not `UnityEditor.Build.Reporting.BuildReport` anymore.

i change code like bellow and it work fine now
```
UnityEditor.Build.Reporting.BuildReport error = BuildPipeline.BuildPlayer(scenesPath, path, build_target, build_options);

// Check if export failed.
bool fail = (error.summary.result == UnityEditor.Build.Reporting.BuildResult.Failed || error.summary.result == UnityEditor.Build.Reporting.BuildResult.Cancelled);
```
to
```
string error = BuildPipeline.BuildPlayer(scenesPath, path, build_target, build_options);

// Check if export failed.
bool fail = (string.IsNullOrEmpty(error) == false);
```

**Comment by nunomonteiro** [comment]
Hi there,
Please try the latest release. The code was bundled in a DLL so you don't even have to worry about trying to fix our issues :)

Let me know how it goes so I can close this issue.

**Comment by trinhvietvan** [comment]
Thank you 👍

**Comment by trinhvietvan** [comment]
@nunomonteiro hello, i try latest sdk, unity dont show this error on editor, but cant not build with Appcoins/Custom build android. Error show when press Confirm

**Comment by nunomonteiro** [comment]
Hi there,
What is the error you are getting?
What version of Unity are you on?
What is your OS?

What I can infer from the title of this issue is that there is a mix up.
There shouldn't be a CustomBuildMenuItem_2018.cs on your package because you're on Unity 5.6 and should be using the 5.6 package. The only way for that file to pop up would be using the 2018 package of the plugin.

Please make sure that the package you're using matches the Unity version you're on.
There's one for Unity 2018.x, one for Unity 2017.x and one for Unity 5.6

Let me know how it goes!

Cheers,
Nuno

**Comment by trinhvietvan** [comment]
Hello,
Thank for you response.
I use Unity 5.6 but i can't find 5.6 package. On repo only have BDS_AppCoins_Unity_Package_2018.unitypackage :(

**Comment by nunomonteiro** [comment]
Sorry for not being clear.
You're checking the repo but there's a tab with official releases. There you can find all the versions!
You can go directly there clicking [here](https://github.com/Aptoide/bds-unity-plugin/releases)

However, to avoid this issue happens again I already added the other versions directly to the repo.

Let me know how it goes!

Cheers,
Nuno
