### ISSUE TITLE
Exception in thread "main" java.lang.TypeNotPresentException: Type io.reactivex.functions.Consumer not present

### ISSUE THREAD

**Issue by megasoft78** [Aptoide/bds-unity-plugin#2]
Hi,
I'm using BDS Unity Plugin v0.3 and Unity 2018.2.6f1 and I'm getting the following error:
https://pastebin.com/TQafjxm6

I was using the previous version without any issue.

Could you please help me?

**Comment by nunomonteiro** [comment]
Hi,
Really sorry you're having this issue.
Could you please open 
Assets/Plugins/Android/mainTemplate.gradle
and check that after the line
```
implementation fileTree(dir: 'libs', excludes: ['com.android.support.support-annotations*.jar'], include: ['*.jar'])
```
there's the line
```
compile group: 'io.reactivex.rxjava2', name: 'rxjava', version: '2.2.1'
```
?

If there isn't please add it and try again.

Let me know how it goes!

**Comment by megasoft78** [comment]
Hi,
yes it's there.
Here's it is:

```
dependencies {
  implementation fileTree(dir: 'libs', excludes: ['com.android.support.support-annotations*.jar'], include: ['*.jar'])
  compile group: 'io.reactivex.rxjava2', name: 'rxjava', version: '2.2.1'
  **DEPS**
}

```

**Comment by nenovmy** [comment]
I also have the same problem and this lines are present in: 

Assets/AppcoinsUnity/Plugins/Android/mainTemplate.gradle

I added the line also in

Assets/Plugins/Android/mainTemplate.gradle

and now I can build and run the app!

**Comment by nunomonteiro** [comment]
Ok, I wasn't clear enough, my bad, sorry again.
There are two versions of this file. We do that so that if you already have a file of your own, or one generated by other plugin, it doesn't just overwrite it. The one in

```
Assets/AppcoinsUnity/Plugins/Android/mainTemplate.gradle
```

Is ours. What we do when the plugin is integrated is check it against the one existing on

```
Assets/Plugins/Android/mainTemplate.gradle
```

And try to merge our changes with the existing one as best as possible.
Please make sure that you are checking the one in

```
Assets/Plugins/Android/mainTemplate.gradle
```

As this is the one that gets used by Unity when generating the gradle project.

**Comment by nenovmy** [comment]
@nunomonteiro yes I tried this and it worked. With this plugin I still have the bug with the "transaction in progress". Should I open a new ticket for this?
The bug is as follows:

1) I try to buy an item (without enough ETH) and it opens the CC form.
2) I cancel the transaction with the cancel button
3) I try later to buy the same item -> a window is shown with the message "transaction in progress". In a while this window disappears and nothing else happens, so this item can not be purchased anymore...

**Comment by megasoft78** [comment]
Hi,
Thank you!
It's working now! :)
I have another small issue to report:
When I click on buy and I try credit card and then cancel, if I try again to buy the same item it doesn't prompt to buy but show immediatelly the processing message and disappear after few seconds.
How can I fix it?

**Comment by nunomonteiro** [comment]
Hey guys!

Sorry for the time it took to get back to you.
This was an error on the wallet and not the plugin. The error has been spotted and fixed, thanks to your help! Expect a new wallet release by the end of this week or beginning of next week.

When the new version is out I'll return to this issue to comment and close it.

Cheers,
Nuno

**Comment by megasoft78** [comment]
Thank you! :)

**Comment by megasoft78** [comment]
@nunomonteiro On a side note I'm experiencing an issue with Backoffice:
When I open the Dashboard using Chrome 69.0.3497.81 (64 bit) on Windows 10, the website get stuck using all CPU and I can't move to a different page. I have to force close the page and re-open.

**Comment by nunomonteiro** [comment]
Hi guys,
I've notified the team working on the portal about this issue and they're on top of it!
Regarding the wallet, a new release is scheduled for next Monday, 10th of September.
When it's out i'll come back here to let you know and then I'll close the issue.

Cheers,
Nuno

**Comment by nunomonteiro** [comment]
Hey guys!
The new version of the wallet, with the fix, was released on the Aptoide store and should be showing up on Google Play anytime soon!
Closing this issue until further notice.

Cheers,
Nuno
