### ISSUE TITLE
Wallet blocked if the transaction get stuck

### ISSUE THREAD

**Issue by megasoft78** [Aptoide/bds-unity-plugin#6]
Hi,
I'm experience issues on some wallets.
It seems that if a transaction get stuck you are not able to do that transaction anymore.
It's like stuck. I tried with latest version and I'm getting the same issue.
It wait forever with the message :
Details checked
Receiving your item...

Could you please help me?

I can't keep creating new wallets every time it get stuck. :(

**Comment by nunomonteiro** [comment]
Hello,
Sorry for the late reply. After internal talks with the team, I figured this issue is related to the wallet and not the plugin by itself.
Could you please post it here: 
https://github.com/Aptoide/appcoins-wallet-android/issues/
Thanks!

Also please make sure you have the latest version of the wallet (1.2.0.14) that was released on October 31st.

Cheers,
Nuno
